"""Add timestamps to all tables

Revision ID: 4ba4ef1bc9b8
Revises: 7ab7ef33d9e1
Create Date: 2025-11-16 13:02:50.184891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ba4ef1bc9b8'
down_revision: Union[str, Sequence[str], None] = '7ab7ef33d9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('daily_prices', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('financial_statements', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('financial_statements', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('stocks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('stocks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'updated_at')
    op.drop_column('stocks', 'created_at')
    op.drop_column('financial_statements', 'updated_at')
    op.drop_column('financial_statements', 'created_at')
    op.drop_column('daily_prices', 'updated_at')
    op.drop_column('daily_prices', 'created_at')
    # ### end Alembic commands ###
