"""Create stocks tables

Revision ID: 7ab7ef33d9e1
Revises: 
Create Date: 2025-11-16 12:55:52.219390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab7ef33d9e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('market', sa.Enum('KOSPI', 'KOSDAQ', name='marketenum'), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('no_fs', sa.Boolean(), nullable=True),
    sa.Column('fs_score', sa.Integer(), nullable=True),
    sa.Column('vcp_score', sa.Integer(), nullable=True),
    sa.Column('trend_template_passed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('ma_50', sa.Float(), nullable=True),
    sa.Column('ma_150', sa.Float(), nullable=True),
    sa.Column('ma_200', sa.Float(), nullable=True),
    sa.Column('ma_200_20d_ago', sa.Float(), nullable=True),
    sa.Column('is_ma_200_bullish', sa.Boolean(), nullable=True),
    sa.Column('week_52_high', sa.Float(), nullable=True),
    sa.Column('is_near_week_52_high', sa.Boolean(), nullable=True),
    sa.Column('week_52_low', sa.Float(), nullable=True),
    sa.Column('is_above_week_52_low_threshold', sa.Boolean(), nullable=True),
    sa.Column('roc_252', sa.Float(), nullable=True),
    sa.Column('roc_126', sa.Float(), nullable=True),
    sa.Column('roc_63', sa.Float(), nullable=True),
    sa.Column('roc_21', sa.Float(), nullable=True),
    sa.Column('rs_momentum', sa.Float(), nullable=True),
    sa.Column('rs_rank', sa.Integer(), nullable=True),
    sa.Column('rs_grade', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='_stock_date_uc')
    )
    op.create_index('ix_daily_prices_date', 'daily_prices', ['date'], unique=False)
    op.create_index(op.f('ix_daily_prices_id'), 'daily_prices', ['id'], unique=False)
    op.create_index('ix_daily_prices_stock_id_date', 'daily_prices', ['stock_id', 'date'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('is_revenue_better_than_tm1_quarter', sa.Boolean(), nullable=True),
    sa.Column('is_revenue_tm1_quarter_better_than_tm2_quarter', sa.Boolean(), nullable=True),
    sa.Column('is_revenue_tm2_quarter_better_than_tm3_quarter', sa.Boolean(), nullable=True),
    sa.Column('is_revenue_this_year_better_than_last_year', sa.Boolean(), nullable=True),
    sa.Column('is_revenue_this_quarter_better_than_year_before_quarter', sa.Boolean(), nullable=True),
    sa.Column('revenue_growth_rate_this_quarter', sa.Float(), nullable=True),
    sa.Column('revenue_growth_rate_tm1_quarter', sa.Float(), nullable=True),
    sa.Column('revenue_growth_rate_tm2_quarter', sa.Float(), nullable=True),
    sa.Column('revenue_growth_rate_tm3_quarter', sa.Float(), nullable=True),
    sa.Column('is_revenue_growth_rate_better_than_tm1_growth_rate', sa.Boolean(), nullable=True),
    sa.Column('is_revenue_growth_rate_better_than_tm2_growth_rate', sa.Boolean(), nullable=True),
    sa.Column('is_revenue_growth_rate_better_than_tm3_growth_rate', sa.Boolean(), nullable=True),
    sa.Column('is_operating_income_better_than_tm1_quarter', sa.Boolean(), nullable=True),
    sa.Column('is_operating_income_tm1_quarter_better_than_tm2_quarter', sa.Boolean(), nullable=True),
    sa.Column('is_operating_income_tm2_quarter_better_than_tm3_quarter', sa.Boolean(), nullable=True),
    sa.Column('is_operating_income_this_year_better_than_last_year', sa.Boolean(), nullable=True),
    sa.Column('is_operating_income_this_quarter_better_than_year_before_quarter', sa.Boolean(), nullable=True),
    sa.Column('operating_income_growth_rate_this_quarter', sa.Float(), nullable=True),
    sa.Column('operating_income_growth_rate_tm1_quarter', sa.Float(), nullable=True),
    sa.Column('operating_income_growth_rate_tm2_quarter', sa.Float(), nullable=True),
    sa.Column('operating_income_growth_rate_tm3_quarter', sa.Float(), nullable=True),
    sa.Column('is_operating_income_growth_rate_better_than_tm1_growth_rate', sa.Boolean(), nullable=True),
    sa.Column('is_operating_income_growth_rate_better_than_tm2_growth_rate', sa.Boolean(), nullable=True),
    sa.Column('is_operating_income_growth_rate_better_than_tm3_growth_rate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'year', 'quarter', name='_stock_year_quarter_uc')
    )
    op.create_index(op.f('ix_financial_statements_id'), 'financial_statements', ['id'], unique=False)
    op.create_index('ix_fs_stock_id_year_quarter', 'financial_statements', ['stock_id', 'year', 'quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fs_stock_id_year_quarter', table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index('ix_daily_prices_stock_id_date', table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_id'), table_name='daily_prices')
    op.drop_index('ix_daily_prices_date', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
